spring:
  application:
    name: world-terrain

  datasource:
    url: jdbc:postgresql://localhost:5432/world_data
    username: nimbus
    password: nimbus123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: world-terrain-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "de.mhus.nimbus"

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

server:
  port: 7083

nimbus:
  world:
    shared:
      secret: ${WORLD_AUTH_SECRET:nimbus-world-secret}

logging:
  level:
    de.mhus.nimbus: DEBUG
    org.springframework.security: DEBUG
