server:
  port: 7081

spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:postgresql://localhost:5432/identity
    username: nimbus
    password: nimbus123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

nimbus:
  jwt:
    secret: ${JWT_SECRET:change-this-in-production-environment}

logging:
  level:
    de.mhus.nimbus: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
