server:
  port: 7089

spring:
  application:
    name: world-bridge
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: world-bridge
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

nimbus:
  identity:
    service:
      url: http://localhost:7081
  world:
    terrain:
      service:
        url: http://localhost:7083
    shared:
      secret: nimbus-world-secret
world:
  auth:
    secret: ${WORLD_AUTH_SECRET:world-terrain-secret-key}

logging:
  level:
    de.mhus.nimbus.worldbridge: DEBUG
    org.springframework.kafka: INFO
