/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package de.mhus.nimbus.shared.avro;
@org.apache.avro.specific.AvroGenerated
public enum Environment implements org.apache.avro.generic.GenericEnumSymbol<Environment> {
  DEV, TEST, STAGING, PROD  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Environment\",\"namespace\":\"de.mhus.nimbus.shared.avro\",\"symbols\":[\"DEV\",\"TEST\",\"STAGING\",\"PROD\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
