/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package de.mhus.nimbus.shared.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Schema für Planet-Lookup-Anfragen im Nimbus Registry System */
@org.apache.avro.specific.AvroGenerated
public class PlanetLookupRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2881060393987472743L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PlanetLookupRequest\",\"namespace\":\"de.mhus.nimbus.shared.avro\",\"doc\":\"Schema für Planet-Lookup-Anfragen im Nimbus Registry System\",\"fields\":[{\"name\":\"requestId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Eindeutige ID der Planet-Lookup-Anfrage\"},{\"name\":\"planetName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Name des gesuchten Planeten\"},{\"name\":\"worldName\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Name der spezifischen Welt auf dem Planeten (optional)\",\"default\":null},{\"name\":\"environment\",\"type\":{\"type\":\"enum\",\"name\":\"Environment\",\"symbols\":[\"DEV\",\"TEST\",\"STAGING\",\"PROD\"]},\"doc\":\"Umgebung für die Planet-Lookup-Anfrage\",\"default\":\"DEV\"},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"Zeitstempel der Anfrage in Millisekunden\"},{\"name\":\"requestedBy\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Benutzer oder Service, der die Anfrage gestellt hat\",\"default\":null},{\"name\":\"metadata\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},\"doc\":\"Zusätzliche Metadaten für die Planet-Anfrage\",\"default\":{}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<PlanetLookupRequest> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PlanetLookupRequest> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PlanetLookupRequest> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PlanetLookupRequest> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PlanetLookupRequest> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PlanetLookupRequest to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PlanetLookupRequest from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PlanetLookupRequest instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PlanetLookupRequest fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Eindeutige ID der Planet-Lookup-Anfrage */
  private java.lang.String requestId;
  /** Name des gesuchten Planeten */
  private java.lang.String planetName;
  /** Name der spezifischen Welt auf dem Planeten (optional) */
  private java.lang.String worldName;
  /** Umgebung für die Planet-Lookup-Anfrage */
  private de.mhus.nimbus.shared.avro.Environment environment;
  /** Zeitstempel der Anfrage in Millisekunden */
  private java.time.Instant timestamp;
  /** Benutzer oder Service, der die Anfrage gestellt hat */
  private java.lang.String requestedBy;
  /** Zusätzliche Metadaten für die Planet-Anfrage */
  private java.util.Map<java.lang.String,java.lang.String> metadata;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PlanetLookupRequest() {}

  /**
   * All-args constructor.
   * @param requestId Eindeutige ID der Planet-Lookup-Anfrage
   * @param planetName Name des gesuchten Planeten
   * @param worldName Name der spezifischen Welt auf dem Planeten (optional)
   * @param environment Umgebung für die Planet-Lookup-Anfrage
   * @param timestamp Zeitstempel der Anfrage in Millisekunden
   * @param requestedBy Benutzer oder Service, der die Anfrage gestellt hat
   * @param metadata Zusätzliche Metadaten für die Planet-Anfrage
   */
  public PlanetLookupRequest(java.lang.String requestId, java.lang.String planetName, java.lang.String worldName, de.mhus.nimbus.shared.avro.Environment environment, java.time.Instant timestamp, java.lang.String requestedBy, java.util.Map<java.lang.String,java.lang.String> metadata) {
    this.requestId = requestId;
    this.planetName = planetName;
    this.worldName = worldName;
    this.environment = environment;
    this.timestamp = timestamp.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.requestedBy = requestedBy;
    this.metadata = metadata;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return requestId;
    case 1: return planetName;
    case 2: return worldName;
    case 3: return environment;
    case 4: return timestamp;
    case 5: return requestedBy;
    case 6: return metadata;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: requestId = value$ != null ? value$.toString() : null; break;
    case 1: planetName = value$ != null ? value$.toString() : null; break;
    case 2: worldName = value$ != null ? value$.toString() : null; break;
    case 3: environment = (de.mhus.nimbus.shared.avro.Environment)value$; break;
    case 4: timestamp = (java.time.Instant)value$; break;
    case 5: requestedBy = value$ != null ? value$.toString() : null; break;
    case 6: metadata = (java.util.Map<java.lang.String,java.lang.String>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'requestId' field.
   * @return Eindeutige ID der Planet-Lookup-Anfrage
   */
  public java.lang.String getRequestId() {
    return requestId;
  }



  /**
   * Gets the value of the 'planetName' field.
   * @return Name des gesuchten Planeten
   */
  public java.lang.String getPlanetName() {
    return planetName;
  }



  /**
   * Gets the value of the 'worldName' field.
   * @return Name der spezifischen Welt auf dem Planeten (optional)
   */
  public java.lang.String getWorldName() {
    return worldName;
  }



  /**
   * Gets the value of the 'environment' field.
   * @return Umgebung für die Planet-Lookup-Anfrage
   */
  public de.mhus.nimbus.shared.avro.Environment getEnvironment() {
    return environment;
  }



  /**
   * Gets the value of the 'timestamp' field.
   * @return Zeitstempel der Anfrage in Millisekunden
   */
  public java.time.Instant getTimestamp() {
    return timestamp;
  }



  /**
   * Gets the value of the 'requestedBy' field.
   * @return Benutzer oder Service, der die Anfrage gestellt hat
   */
  public java.lang.String getRequestedBy() {
    return requestedBy;
  }



  /**
   * Gets the value of the 'metadata' field.
   * @return Zusätzliche Metadaten für die Planet-Anfrage
   */
  public java.util.Map<java.lang.String,java.lang.String> getMetadata() {
    return metadata;
  }



  /**
   * Creates a new PlanetLookupRequest RecordBuilder.
   * @return A new PlanetLookupRequest RecordBuilder
   */
  public static de.mhus.nimbus.shared.avro.PlanetLookupRequest.Builder newBuilder() {
    return new de.mhus.nimbus.shared.avro.PlanetLookupRequest.Builder();
  }

  /**
   * Creates a new PlanetLookupRequest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PlanetLookupRequest RecordBuilder
   */
  public static de.mhus.nimbus.shared.avro.PlanetLookupRequest.Builder newBuilder(de.mhus.nimbus.shared.avro.PlanetLookupRequest.Builder other) {
    if (other == null) {
      return new de.mhus.nimbus.shared.avro.PlanetLookupRequest.Builder();
    } else {
      return new de.mhus.nimbus.shared.avro.PlanetLookupRequest.Builder(other);
    }
  }

  /**
   * Creates a new PlanetLookupRequest RecordBuilder by copying an existing PlanetLookupRequest instance.
   * @param other The existing instance to copy.
   * @return A new PlanetLookupRequest RecordBuilder
   */
  public static de.mhus.nimbus.shared.avro.PlanetLookupRequest.Builder newBuilder(de.mhus.nimbus.shared.avro.PlanetLookupRequest other) {
    if (other == null) {
      return new de.mhus.nimbus.shared.avro.PlanetLookupRequest.Builder();
    } else {
      return new de.mhus.nimbus.shared.avro.PlanetLookupRequest.Builder(other);
    }
  }

  /**
   * RecordBuilder for PlanetLookupRequest instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PlanetLookupRequest>
    implements org.apache.avro.data.RecordBuilder<PlanetLookupRequest> {

    /** Eindeutige ID der Planet-Lookup-Anfrage */
    private java.lang.String requestId;
    /** Name des gesuchten Planeten */
    private java.lang.String planetName;
    /** Name der spezifischen Welt auf dem Planeten (optional) */
    private java.lang.String worldName;
    /** Umgebung für die Planet-Lookup-Anfrage */
    private de.mhus.nimbus.shared.avro.Environment environment;
    /** Zeitstempel der Anfrage in Millisekunden */
    private java.time.Instant timestamp;
    /** Benutzer oder Service, der die Anfrage gestellt hat */
    private java.lang.String requestedBy;
    /** Zusätzliche Metadaten für die Planet-Anfrage */
    private java.util.Map<java.lang.String,java.lang.String> metadata;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(de.mhus.nimbus.shared.avro.PlanetLookupRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.requestId)) {
        this.requestId = data().deepCopy(fields()[0].schema(), other.requestId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.planetName)) {
        this.planetName = data().deepCopy(fields()[1].schema(), other.planetName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.worldName)) {
        this.worldName = data().deepCopy(fields()[2].schema(), other.worldName);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.environment)) {
        this.environment = data().deepCopy(fields()[3].schema(), other.environment);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[4].schema(), other.timestamp);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.requestedBy)) {
        this.requestedBy = data().deepCopy(fields()[5].schema(), other.requestedBy);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.metadata)) {
        this.metadata = data().deepCopy(fields()[6].schema(), other.metadata);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing PlanetLookupRequest instance
     * @param other The existing instance to copy.
     */
    private Builder(de.mhus.nimbus.shared.avro.PlanetLookupRequest other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.requestId)) {
        this.requestId = data().deepCopy(fields()[0].schema(), other.requestId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.planetName)) {
        this.planetName = data().deepCopy(fields()[1].schema(), other.planetName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.worldName)) {
        this.worldName = data().deepCopy(fields()[2].schema(), other.worldName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.environment)) {
        this.environment = data().deepCopy(fields()[3].schema(), other.environment);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[4].schema(), other.timestamp);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.requestedBy)) {
        this.requestedBy = data().deepCopy(fields()[5].schema(), other.requestedBy);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.metadata)) {
        this.metadata = data().deepCopy(fields()[6].schema(), other.metadata);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'requestId' field.
      * Eindeutige ID der Planet-Lookup-Anfrage
      * @return The value.
      */
    public java.lang.String getRequestId() {
      return requestId;
    }


    /**
      * Sets the value of the 'requestId' field.
      * Eindeutige ID der Planet-Lookup-Anfrage
      * @param value The value of 'requestId'.
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlanetLookupRequest.Builder setRequestId(java.lang.String value) {
      validate(fields()[0], value);
      this.requestId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'requestId' field has been set.
      * Eindeutige ID der Planet-Lookup-Anfrage
      * @return True if the 'requestId' field has been set, false otherwise.
      */
    public boolean hasRequestId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'requestId' field.
      * Eindeutige ID der Planet-Lookup-Anfrage
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlanetLookupRequest.Builder clearRequestId() {
      requestId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'planetName' field.
      * Name des gesuchten Planeten
      * @return The value.
      */
    public java.lang.String getPlanetName() {
      return planetName;
    }


    /**
      * Sets the value of the 'planetName' field.
      * Name des gesuchten Planeten
      * @param value The value of 'planetName'.
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlanetLookupRequest.Builder setPlanetName(java.lang.String value) {
      validate(fields()[1], value);
      this.planetName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'planetName' field has been set.
      * Name des gesuchten Planeten
      * @return True if the 'planetName' field has been set, false otherwise.
      */
    public boolean hasPlanetName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'planetName' field.
      * Name des gesuchten Planeten
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlanetLookupRequest.Builder clearPlanetName() {
      planetName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'worldName' field.
      * Name der spezifischen Welt auf dem Planeten (optional)
      * @return The value.
      */
    public java.lang.String getWorldName() {
      return worldName;
    }


    /**
      * Sets the value of the 'worldName' field.
      * Name der spezifischen Welt auf dem Planeten (optional)
      * @param value The value of 'worldName'.
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlanetLookupRequest.Builder setWorldName(java.lang.String value) {
      validate(fields()[2], value);
      this.worldName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'worldName' field has been set.
      * Name der spezifischen Welt auf dem Planeten (optional)
      * @return True if the 'worldName' field has been set, false otherwise.
      */
    public boolean hasWorldName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'worldName' field.
      * Name der spezifischen Welt auf dem Planeten (optional)
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlanetLookupRequest.Builder clearWorldName() {
      worldName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'environment' field.
      * Umgebung für die Planet-Lookup-Anfrage
      * @return The value.
      */
    public de.mhus.nimbus.shared.avro.Environment getEnvironment() {
      return environment;
    }


    /**
      * Sets the value of the 'environment' field.
      * Umgebung für die Planet-Lookup-Anfrage
      * @param value The value of 'environment'.
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlanetLookupRequest.Builder setEnvironment(de.mhus.nimbus.shared.avro.Environment value) {
      validate(fields()[3], value);
      this.environment = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'environment' field has been set.
      * Umgebung für die Planet-Lookup-Anfrage
      * @return True if the 'environment' field has been set, false otherwise.
      */
    public boolean hasEnvironment() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'environment' field.
      * Umgebung für die Planet-Lookup-Anfrage
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlanetLookupRequest.Builder clearEnvironment() {
      environment = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * Zeitstempel der Anfrage in Millisekunden
      * @return The value.
      */
    public java.time.Instant getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * Zeitstempel der Anfrage in Millisekunden
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlanetLookupRequest.Builder setTimestamp(java.time.Instant value) {
      validate(fields()[4], value);
      this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * Zeitstempel der Anfrage in Millisekunden
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * Zeitstempel der Anfrage in Millisekunden
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlanetLookupRequest.Builder clearTimestamp() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'requestedBy' field.
      * Benutzer oder Service, der die Anfrage gestellt hat
      * @return The value.
      */
    public java.lang.String getRequestedBy() {
      return requestedBy;
    }


    /**
      * Sets the value of the 'requestedBy' field.
      * Benutzer oder Service, der die Anfrage gestellt hat
      * @param value The value of 'requestedBy'.
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlanetLookupRequest.Builder setRequestedBy(java.lang.String value) {
      validate(fields()[5], value);
      this.requestedBy = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'requestedBy' field has been set.
      * Benutzer oder Service, der die Anfrage gestellt hat
      * @return True if the 'requestedBy' field has been set, false otherwise.
      */
    public boolean hasRequestedBy() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'requestedBy' field.
      * Benutzer oder Service, der die Anfrage gestellt hat
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlanetLookupRequest.Builder clearRequestedBy() {
      requestedBy = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'metadata' field.
      * Zusätzliche Metadaten für die Planet-Anfrage
      * @return The value.
      */
    public java.util.Map<java.lang.String,java.lang.String> getMetadata() {
      return metadata;
    }


    /**
      * Sets the value of the 'metadata' field.
      * Zusätzliche Metadaten für die Planet-Anfrage
      * @param value The value of 'metadata'.
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlanetLookupRequest.Builder setMetadata(java.util.Map<java.lang.String,java.lang.String> value) {
      validate(fields()[6], value);
      this.metadata = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'metadata' field has been set.
      * Zusätzliche Metadaten für die Planet-Anfrage
      * @return True if the 'metadata' field has been set, false otherwise.
      */
    public boolean hasMetadata() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'metadata' field.
      * Zusätzliche Metadaten für die Planet-Anfrage
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlanetLookupRequest.Builder clearMetadata() {
      metadata = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PlanetLookupRequest build() {
      try {
        PlanetLookupRequest record = new PlanetLookupRequest();
        record.requestId = fieldSetFlags()[0] ? this.requestId : (java.lang.String) defaultValue(fields()[0]);
        record.planetName = fieldSetFlags()[1] ? this.planetName : (java.lang.String) defaultValue(fields()[1]);
        record.worldName = fieldSetFlags()[2] ? this.worldName : (java.lang.String) defaultValue(fields()[2]);
        record.environment = fieldSetFlags()[3] ? this.environment : (de.mhus.nimbus.shared.avro.Environment) defaultValue(fields()[3]);
        record.timestamp = fieldSetFlags()[4] ? this.timestamp : (java.time.Instant) defaultValue(fields()[4]);
        record.requestedBy = fieldSetFlags()[5] ? this.requestedBy : (java.lang.String) defaultValue(fields()[5]);
        record.metadata = fieldSetFlags()[6] ? this.metadata : (java.util.Map<java.lang.String,java.lang.String>) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PlanetLookupRequest>
    WRITER$ = (org.apache.avro.io.DatumWriter<PlanetLookupRequest>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PlanetLookupRequest>
    READER$ = (org.apache.avro.io.DatumReader<PlanetLookupRequest>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










