/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package de.mhus.nimbus.shared.avro;
@org.apache.avro.specific.AvroGenerated
public enum PlanetRegistrationStatus implements org.apache.avro.generic.GenericEnumSymbol<PlanetRegistrationStatus> {
  SUCCESS, PLANET_ALREADY_EXISTS, WORLD_ALREADY_EXISTS, VALIDATION_ERROR, ERROR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PlanetRegistrationStatus\",\"namespace\":\"de.mhus.nimbus.shared.avro\",\"symbols\":[\"SUCCESS\",\"PLANET_ALREADY_EXISTS\",\"WORLD_ALREADY_EXISTS\",\"VALIDATION_ERROR\",\"ERROR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
