/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package de.mhus.nimbus.shared.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Schema für PlayerCharacter-Lookup-Anfragen im Nimbus Identity System */
@org.apache.avro.specific.AvroGenerated
public class PlayerCharacterLookupRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6194133197256790495L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PlayerCharacterLookupRequest\",\"namespace\":\"de.mhus.nimbus.shared.avro\",\"doc\":\"Schema für PlayerCharacter-Lookup-Anfragen im Nimbus Identity System\",\"fields\":[{\"name\":\"requestId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Eindeutige ID der PlayerCharacter-Lookup-Anfrage\"},{\"name\":\"characterId\",\"type\":[\"null\",\"long\"],\"doc\":\"ID des gesuchten PlayerCharacters (optional)\",\"default\":null},{\"name\":\"characterName\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Name des gesuchten PlayerCharacters (optional)\",\"default\":null},{\"name\":\"userId\",\"type\":[\"null\",\"long\"],\"doc\":\"User-ID für die Suche nach allen Characters eines Users (optional)\",\"default\":null},{\"name\":\"currentPlanet\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Planet für die Suche nach Characters auf einem bestimmten Planeten (optional)\",\"default\":null},{\"name\":\"currentWorldId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Welt-ID für die Suche nach Characters in einer bestimmten Welt (optional)\",\"default\":null},{\"name\":\"activeOnly\",\"type\":\"boolean\",\"doc\":\"Nur aktive Characters zurückgeben\",\"default\":true},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"Zeitstempel der Anfrage in Millisekunden\"},{\"name\":\"requestedBy\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Service oder User der die Anfrage stellt\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<PlayerCharacterLookupRequest> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PlayerCharacterLookupRequest> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PlayerCharacterLookupRequest> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PlayerCharacterLookupRequest> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PlayerCharacterLookupRequest> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PlayerCharacterLookupRequest to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PlayerCharacterLookupRequest from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PlayerCharacterLookupRequest instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PlayerCharacterLookupRequest fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Eindeutige ID der PlayerCharacter-Lookup-Anfrage */
  private java.lang.String requestId;
  /** ID des gesuchten PlayerCharacters (optional) */
  private java.lang.Long characterId;
  /** Name des gesuchten PlayerCharacters (optional) */
  private java.lang.String characterName;
  /** User-ID für die Suche nach allen Characters eines Users (optional) */
  private java.lang.Long userId;
  /** Planet für die Suche nach Characters auf einem bestimmten Planeten (optional) */
  private java.lang.String currentPlanet;
  /** Welt-ID für die Suche nach Characters in einer bestimmten Welt (optional) */
  private java.lang.String currentWorldId;
  /** Nur aktive Characters zurückgeben */
  private boolean activeOnly;
  /** Zeitstempel der Anfrage in Millisekunden */
  private java.time.Instant timestamp;
  /** Service oder User der die Anfrage stellt */
  private java.lang.String requestedBy;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PlayerCharacterLookupRequest() {}

  /**
   * All-args constructor.
   * @param requestId Eindeutige ID der PlayerCharacter-Lookup-Anfrage
   * @param characterId ID des gesuchten PlayerCharacters (optional)
   * @param characterName Name des gesuchten PlayerCharacters (optional)
   * @param userId User-ID für die Suche nach allen Characters eines Users (optional)
   * @param currentPlanet Planet für die Suche nach Characters auf einem bestimmten Planeten (optional)
   * @param currentWorldId Welt-ID für die Suche nach Characters in einer bestimmten Welt (optional)
   * @param activeOnly Nur aktive Characters zurückgeben
   * @param timestamp Zeitstempel der Anfrage in Millisekunden
   * @param requestedBy Service oder User der die Anfrage stellt
   */
  public PlayerCharacterLookupRequest(java.lang.String requestId, java.lang.Long characterId, java.lang.String characterName, java.lang.Long userId, java.lang.String currentPlanet, java.lang.String currentWorldId, java.lang.Boolean activeOnly, java.time.Instant timestamp, java.lang.String requestedBy) {
    this.requestId = requestId;
    this.characterId = characterId;
    this.characterName = characterName;
    this.userId = userId;
    this.currentPlanet = currentPlanet;
    this.currentWorldId = currentWorldId;
    this.activeOnly = activeOnly;
    this.timestamp = timestamp.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.requestedBy = requestedBy;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return requestId;
    case 1: return characterId;
    case 2: return characterName;
    case 3: return userId;
    case 4: return currentPlanet;
    case 5: return currentWorldId;
    case 6: return activeOnly;
    case 7: return timestamp;
    case 8: return requestedBy;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: requestId = value$ != null ? value$.toString() : null; break;
    case 1: characterId = (java.lang.Long)value$; break;
    case 2: characterName = value$ != null ? value$.toString() : null; break;
    case 3: userId = (java.lang.Long)value$; break;
    case 4: currentPlanet = value$ != null ? value$.toString() : null; break;
    case 5: currentWorldId = value$ != null ? value$.toString() : null; break;
    case 6: activeOnly = (java.lang.Boolean)value$; break;
    case 7: timestamp = (java.time.Instant)value$; break;
    case 8: requestedBy = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'requestId' field.
   * @return Eindeutige ID der PlayerCharacter-Lookup-Anfrage
   */
  public java.lang.String getRequestId() {
    return requestId;
  }



  /**
   * Gets the value of the 'characterId' field.
   * @return ID des gesuchten PlayerCharacters (optional)
   */
  public java.lang.Long getCharacterId() {
    return characterId;
  }



  /**
   * Gets the value of the 'characterName' field.
   * @return Name des gesuchten PlayerCharacters (optional)
   */
  public java.lang.String getCharacterName() {
    return characterName;
  }



  /**
   * Gets the value of the 'userId' field.
   * @return User-ID für die Suche nach allen Characters eines Users (optional)
   */
  public java.lang.Long getUserId() {
    return userId;
  }



  /**
   * Gets the value of the 'currentPlanet' field.
   * @return Planet für die Suche nach Characters auf einem bestimmten Planeten (optional)
   */
  public java.lang.String getCurrentPlanet() {
    return currentPlanet;
  }



  /**
   * Gets the value of the 'currentWorldId' field.
   * @return Welt-ID für die Suche nach Characters in einer bestimmten Welt (optional)
   */
  public java.lang.String getCurrentWorldId() {
    return currentWorldId;
  }



  /**
   * Gets the value of the 'activeOnly' field.
   * @return Nur aktive Characters zurückgeben
   */
  public boolean getActiveOnly() {
    return activeOnly;
  }



  /**
   * Gets the value of the 'timestamp' field.
   * @return Zeitstempel der Anfrage in Millisekunden
   */
  public java.time.Instant getTimestamp() {
    return timestamp;
  }



  /**
   * Gets the value of the 'requestedBy' field.
   * @return Service oder User der die Anfrage stellt
   */
  public java.lang.String getRequestedBy() {
    return requestedBy;
  }



  /**
   * Creates a new PlayerCharacterLookupRequest RecordBuilder.
   * @return A new PlayerCharacterLookupRequest RecordBuilder
   */
  public static de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder newBuilder() {
    return new de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder();
  }

  /**
   * Creates a new PlayerCharacterLookupRequest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PlayerCharacterLookupRequest RecordBuilder
   */
  public static de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder newBuilder(de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder other) {
    if (other == null) {
      return new de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder();
    } else {
      return new de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder(other);
    }
  }

  /**
   * Creates a new PlayerCharacterLookupRequest RecordBuilder by copying an existing PlayerCharacterLookupRequest instance.
   * @param other The existing instance to copy.
   * @return A new PlayerCharacterLookupRequest RecordBuilder
   */
  public static de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder newBuilder(de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest other) {
    if (other == null) {
      return new de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder();
    } else {
      return new de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder(other);
    }
  }

  /**
   * RecordBuilder for PlayerCharacterLookupRequest instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PlayerCharacterLookupRequest>
    implements org.apache.avro.data.RecordBuilder<PlayerCharacterLookupRequest> {

    /** Eindeutige ID der PlayerCharacter-Lookup-Anfrage */
    private java.lang.String requestId;
    /** ID des gesuchten PlayerCharacters (optional) */
    private java.lang.Long characterId;
    /** Name des gesuchten PlayerCharacters (optional) */
    private java.lang.String characterName;
    /** User-ID für die Suche nach allen Characters eines Users (optional) */
    private java.lang.Long userId;
    /** Planet für die Suche nach Characters auf einem bestimmten Planeten (optional) */
    private java.lang.String currentPlanet;
    /** Welt-ID für die Suche nach Characters in einer bestimmten Welt (optional) */
    private java.lang.String currentWorldId;
    /** Nur aktive Characters zurückgeben */
    private boolean activeOnly;
    /** Zeitstempel der Anfrage in Millisekunden */
    private java.time.Instant timestamp;
    /** Service oder User der die Anfrage stellt */
    private java.lang.String requestedBy;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.requestId)) {
        this.requestId = data().deepCopy(fields()[0].schema(), other.requestId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.characterId)) {
        this.characterId = data().deepCopy(fields()[1].schema(), other.characterId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.characterName)) {
        this.characterName = data().deepCopy(fields()[2].schema(), other.characterName);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.userId)) {
        this.userId = data().deepCopy(fields()[3].schema(), other.userId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.currentPlanet)) {
        this.currentPlanet = data().deepCopy(fields()[4].schema(), other.currentPlanet);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.currentWorldId)) {
        this.currentWorldId = data().deepCopy(fields()[5].schema(), other.currentWorldId);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.activeOnly)) {
        this.activeOnly = data().deepCopy(fields()[6].schema(), other.activeOnly);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[7].schema(), other.timestamp);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.requestedBy)) {
        this.requestedBy = data().deepCopy(fields()[8].schema(), other.requestedBy);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
    }

    /**
     * Creates a Builder by copying an existing PlayerCharacterLookupRequest instance
     * @param other The existing instance to copy.
     */
    private Builder(de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.requestId)) {
        this.requestId = data().deepCopy(fields()[0].schema(), other.requestId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.characterId)) {
        this.characterId = data().deepCopy(fields()[1].schema(), other.characterId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.characterName)) {
        this.characterName = data().deepCopy(fields()[2].schema(), other.characterName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.userId)) {
        this.userId = data().deepCopy(fields()[3].schema(), other.userId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.currentPlanet)) {
        this.currentPlanet = data().deepCopy(fields()[4].schema(), other.currentPlanet);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.currentWorldId)) {
        this.currentWorldId = data().deepCopy(fields()[5].schema(), other.currentWorldId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.activeOnly)) {
        this.activeOnly = data().deepCopy(fields()[6].schema(), other.activeOnly);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[7].schema(), other.timestamp);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.requestedBy)) {
        this.requestedBy = data().deepCopy(fields()[8].schema(), other.requestedBy);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'requestId' field.
      * Eindeutige ID der PlayerCharacter-Lookup-Anfrage
      * @return The value.
      */
    public java.lang.String getRequestId() {
      return requestId;
    }


    /**
      * Sets the value of the 'requestId' field.
      * Eindeutige ID der PlayerCharacter-Lookup-Anfrage
      * @param value The value of 'requestId'.
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder setRequestId(java.lang.String value) {
      validate(fields()[0], value);
      this.requestId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'requestId' field has been set.
      * Eindeutige ID der PlayerCharacter-Lookup-Anfrage
      * @return True if the 'requestId' field has been set, false otherwise.
      */
    public boolean hasRequestId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'requestId' field.
      * Eindeutige ID der PlayerCharacter-Lookup-Anfrage
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder clearRequestId() {
      requestId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'characterId' field.
      * ID des gesuchten PlayerCharacters (optional)
      * @return The value.
      */
    public java.lang.Long getCharacterId() {
      return characterId;
    }


    /**
      * Sets the value of the 'characterId' field.
      * ID des gesuchten PlayerCharacters (optional)
      * @param value The value of 'characterId'.
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder setCharacterId(java.lang.Long value) {
      validate(fields()[1], value);
      this.characterId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'characterId' field has been set.
      * ID des gesuchten PlayerCharacters (optional)
      * @return True if the 'characterId' field has been set, false otherwise.
      */
    public boolean hasCharacterId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'characterId' field.
      * ID des gesuchten PlayerCharacters (optional)
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder clearCharacterId() {
      characterId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'characterName' field.
      * Name des gesuchten PlayerCharacters (optional)
      * @return The value.
      */
    public java.lang.String getCharacterName() {
      return characterName;
    }


    /**
      * Sets the value of the 'characterName' field.
      * Name des gesuchten PlayerCharacters (optional)
      * @param value The value of 'characterName'.
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder setCharacterName(java.lang.String value) {
      validate(fields()[2], value);
      this.characterName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'characterName' field has been set.
      * Name des gesuchten PlayerCharacters (optional)
      * @return True if the 'characterName' field has been set, false otherwise.
      */
    public boolean hasCharacterName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'characterName' field.
      * Name des gesuchten PlayerCharacters (optional)
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder clearCharacterName() {
      characterName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'userId' field.
      * User-ID für die Suche nach allen Characters eines Users (optional)
      * @return The value.
      */
    public java.lang.Long getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * User-ID für die Suche nach allen Characters eines Users (optional)
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder setUserId(java.lang.Long value) {
      validate(fields()[3], value);
      this.userId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * User-ID für die Suche nach allen Characters eines Users (optional)
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'userId' field.
      * User-ID für die Suche nach allen Characters eines Users (optional)
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'currentPlanet' field.
      * Planet für die Suche nach Characters auf einem bestimmten Planeten (optional)
      * @return The value.
      */
    public java.lang.String getCurrentPlanet() {
      return currentPlanet;
    }


    /**
      * Sets the value of the 'currentPlanet' field.
      * Planet für die Suche nach Characters auf einem bestimmten Planeten (optional)
      * @param value The value of 'currentPlanet'.
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder setCurrentPlanet(java.lang.String value) {
      validate(fields()[4], value);
      this.currentPlanet = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'currentPlanet' field has been set.
      * Planet für die Suche nach Characters auf einem bestimmten Planeten (optional)
      * @return True if the 'currentPlanet' field has been set, false otherwise.
      */
    public boolean hasCurrentPlanet() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'currentPlanet' field.
      * Planet für die Suche nach Characters auf einem bestimmten Planeten (optional)
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder clearCurrentPlanet() {
      currentPlanet = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'currentWorldId' field.
      * Welt-ID für die Suche nach Characters in einer bestimmten Welt (optional)
      * @return The value.
      */
    public java.lang.String getCurrentWorldId() {
      return currentWorldId;
    }


    /**
      * Sets the value of the 'currentWorldId' field.
      * Welt-ID für die Suche nach Characters in einer bestimmten Welt (optional)
      * @param value The value of 'currentWorldId'.
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder setCurrentWorldId(java.lang.String value) {
      validate(fields()[5], value);
      this.currentWorldId = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'currentWorldId' field has been set.
      * Welt-ID für die Suche nach Characters in einer bestimmten Welt (optional)
      * @return True if the 'currentWorldId' field has been set, false otherwise.
      */
    public boolean hasCurrentWorldId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'currentWorldId' field.
      * Welt-ID für die Suche nach Characters in einer bestimmten Welt (optional)
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder clearCurrentWorldId() {
      currentWorldId = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'activeOnly' field.
      * Nur aktive Characters zurückgeben
      * @return The value.
      */
    public boolean getActiveOnly() {
      return activeOnly;
    }


    /**
      * Sets the value of the 'activeOnly' field.
      * Nur aktive Characters zurückgeben
      * @param value The value of 'activeOnly'.
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder setActiveOnly(boolean value) {
      validate(fields()[6], value);
      this.activeOnly = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'activeOnly' field has been set.
      * Nur aktive Characters zurückgeben
      * @return True if the 'activeOnly' field has been set, false otherwise.
      */
    public boolean hasActiveOnly() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'activeOnly' field.
      * Nur aktive Characters zurückgeben
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder clearActiveOnly() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * Zeitstempel der Anfrage in Millisekunden
      * @return The value.
      */
    public java.time.Instant getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * Zeitstempel der Anfrage in Millisekunden
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder setTimestamp(java.time.Instant value) {
      validate(fields()[7], value);
      this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * Zeitstempel der Anfrage in Millisekunden
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * Zeitstempel der Anfrage in Millisekunden
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder clearTimestamp() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'requestedBy' field.
      * Service oder User der die Anfrage stellt
      * @return The value.
      */
    public java.lang.String getRequestedBy() {
      return requestedBy;
    }


    /**
      * Sets the value of the 'requestedBy' field.
      * Service oder User der die Anfrage stellt
      * @param value The value of 'requestedBy'.
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder setRequestedBy(java.lang.String value) {
      validate(fields()[8], value);
      this.requestedBy = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'requestedBy' field has been set.
      * Service oder User der die Anfrage stellt
      * @return True if the 'requestedBy' field has been set, false otherwise.
      */
    public boolean hasRequestedBy() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'requestedBy' field.
      * Service oder User der die Anfrage stellt
      * @return This builder.
      */
    public de.mhus.nimbus.shared.avro.PlayerCharacterLookupRequest.Builder clearRequestedBy() {
      requestedBy = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PlayerCharacterLookupRequest build() {
      try {
        PlayerCharacterLookupRequest record = new PlayerCharacterLookupRequest();
        record.requestId = fieldSetFlags()[0] ? this.requestId : (java.lang.String) defaultValue(fields()[0]);
        record.characterId = fieldSetFlags()[1] ? this.characterId : (java.lang.Long) defaultValue(fields()[1]);
        record.characterName = fieldSetFlags()[2] ? this.characterName : (java.lang.String) defaultValue(fields()[2]);
        record.userId = fieldSetFlags()[3] ? this.userId : (java.lang.Long) defaultValue(fields()[3]);
        record.currentPlanet = fieldSetFlags()[4] ? this.currentPlanet : (java.lang.String) defaultValue(fields()[4]);
        record.currentWorldId = fieldSetFlags()[5] ? this.currentWorldId : (java.lang.String) defaultValue(fields()[5]);
        record.activeOnly = fieldSetFlags()[6] ? this.activeOnly : (java.lang.Boolean) defaultValue(fields()[6]);
        record.timestamp = fieldSetFlags()[7] ? this.timestamp : (java.time.Instant) defaultValue(fields()[7]);
        record.requestedBy = fieldSetFlags()[8] ? this.requestedBy : (java.lang.String) defaultValue(fields()[8]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PlayerCharacterLookupRequest>
    WRITER$ = (org.apache.avro.io.DatumWriter<PlayerCharacterLookupRequest>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PlayerCharacterLookupRequest>
    READER$ = (org.apache.avro.io.DatumReader<PlayerCharacterLookupRequest>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










