/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package de.mhus.nimbus.shared.avro;
@org.apache.avro.specific.AvroGenerated
public enum PublicKeyStatus implements org.apache.avro.generic.GenericEnumSymbol<PublicKeyStatus> {
  SUCCESS, ERROR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PublicKeyStatus\",\"namespace\":\"de.mhus.nimbus.shared.avro\",\"symbols\":[\"SUCCESS\",\"ERROR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
